[tox]
#envlist=py36, py37, py38, py39
envlist=py38

[isort]
profile = black
line_length = 99
known_first_party = tox,tests

[testenv]
setenv= LC_ALL = C
passenv=
    TESSDATA_PREFIX
    LIBPATH
    INCLUDE
deps=
    Cython
    Pillow
    setuptools
commands={envpython} setup.py test
